"""
L481 — Hybrid H1 = R3 (RG saddle FP) (X) R7 (Holographic UV-IR mixing)
Test: tau_q(sigma_0) running with holographic constraint.

Design (independent toy, no formula transplant from L46/L22):
    Let s = ln(sigma_0/sigma_*) be a dimensionless scale variable, where
    sigma_0 plays the role of an environmental "scale" (energy or 1/length).

    Two fixed points (R3 saddle):
        UV FP at s -> +inf : tau_q -> tau_UV  (Planck)
        IR FP at s -> -inf : tau_q -> tau_IR  (Hubble)

    Holographic constraint (R7):
        log10(tau_UV) + log10(tau_IR) = C_holo  (UV-IR pair product fixed
        by horizon-area / Newton constant; we adopt the standard CKN-style
        anchor that fixes the product, not each end individually).

    Running form (R3 saddle FP with single shape parameter):
        log10(tau_q)(s) = 0.5*(log10(tau_UV)+log10(tau_IR))
                       + 0.5*(log10(tau_UV)-log10(tau_IR)) * f(s; w)

        f(s; w) = tanh(s/w) — generic single-parameter running between two
        fixed points consistent with a saddle topology of the beta-function.

    Cluster dip (R7 holographic correction):
        Holographic IR-UV mixing yields a *non-monotone* admixture near
        the entanglement-entropy crossover. We add a perturbative
        Gaussian dip centred at s = s_dip with depth d (in dex) and
        width sigma_dip, generated by the UV-IR pair coupling. This is
        the *natural emergence* test: the dip should appear *at the
        cluster scale window* without fine-tuned position, and must
        not destroy the cosmic / micro endpoints.

Test protocol (4-value):
    Given anchors:
        s_cosmic, target log10(tau_q_cosmic)
        s_cluster, target log10(tau_q_cluster)
        s_galactic, target log10(tau_q_galactic)
        s_new (NEW PREDICTION POINT), target band (predicted by SQMH structure)

    Free parameters: { log10(tau_UV), log10(tau_IR), w, s_dip, d, sigma_dip }
        with holographic constraint log10(tau_UV)+log10(tau_IR) = C_holo
        => 5 free params after constraint.

    Pass criterion: |residual| < tol_dex at each of the 4 anchors.

Honesty: this is a TOY. We test whether the 6-dim (constrained 5-dim)
H1 functional family is *expressive enough* to simultaneously pass 4
independent anchor constraints. We do NOT claim physical derivation.
"""

import os, json, math
import numpy as np
from scipy.optimize import minimize


# ---------- Anchor scales (4-value) ----------
# We work in s = log10(L/L_ref) with L_ref = 1 m (length scale).
# tau_q is in seconds.
#
# Anchor 1 (COSMIC, ~Hubble): L ~ 4.4e26 m, tau ~ 4.4e17 s
# Anchor 2 (CLUSTER): L ~ 3e22 m (~ Mpc), tau ~ 3e13 s  (cluster transition - DIP region)
# Anchor 3 (GALACTIC, SPARC a0): L ~ c^2/a0 ~ 7.5e26 m -> too close to cosmic;
#    use galactic dynamical scale L_gal ~ 3e20 m (10 kpc), tau_gal ~ 3e11 s
# Anchor 4 (NEW PREDICTION, ATOMIC bridge): laboratory L ~ 1e-10 m, tau ~ 1e-18 s
#
# These 4 anchors span ~36 dex in length and ~35 dex in tau.

ANCHORS = [
    # (name, s = log10 L[m], target log10 tau_q[s], tol_dex)
    # Anchor logic: tau_q is SQMH "metabolism period". At UV (Planck, L=L_P=-35.2)
    # tau_q = t_P = -43.27. At IR (Hubble, L=R_H=26.64) tau_q = t_H = 17.64.
    # Intermediate anchors test the *running* shape, not light-crossing.
    #
    # cosmic anchor: at Hubble scale, tau_q = Hubble time
    # cluster anchor: SQMH cluster-dip prediction — tau_q dips BELOW the
    #   smooth running curve by ~1 dex (decoherence depression).
    #   At L = 3e22 m smooth running predicts ~14 dex; with dip ~13 dex.
    # galactic anchor: SPARC a0 connection — at galactic dynamical scale
    #   ~10 kpc (3e20 m), SQMH predicts tau_q on the smooth running curve
    #   between micro and cluster. We use ~9 dex (between micro running
    #   and cluster dip — natural for transition regime).
    # NEW PREDICTION: atomic Lamb-shift bridge L=1 Bohr radius (5.3e-11 m).
    #   SQMH §III microbridge requires tau_q = Planck time here (micro
    #   physics is still micro at atomic L). Target: -43.27 ± 1.0.
    ("cosmic",     math.log10(4.4e26), 17.64, 0.30),
    ("cluster",    math.log10(3.0e22), 13.0,  0.50),   # DIP region (depressed)
    ("galactic",   math.log10(3.0e20),  9.0,  0.50),
    ("new_atomic", math.log10(5.3e-11),-43.27, 1.0),
]

# Holographic UV-IR pair anchor:
# log10(tau_UV at L_P) + log10(tau_IR at R_H) = -43.27 + 17.64 = -25.63
C_HOLO = -43.27 + 17.64  # = -25.63 dex


def log10_tau_model(s, params):
    """params = (logUV, w, s_dip, d, sigma_dip).
       logIR is fixed by holographic constraint: logIR = C_HOLO - logUV.
    """
    logUV, w, s_dip, d, sig_dip = params
    logIR = C_HOLO - logUV
    mid = 0.5 * (logUV + logIR)         # = C_HOLO/2
    half = 0.5 * (logUV - logIR)
    base = mid + half * np.tanh(s / w)
    # holographic correction: Gaussian dip (negative bump in tau)
    correction = -d * np.exp(-0.5 * ((s - s_dip) / sig_dip) ** 2)
    return base + correction


def chi2(params, anchors=ANCHORS):
    logUV, w, s_dip, d, sig_dip = params
    total = 0.0
    for (_, s, t_target, tol) in anchors:
        t_model = log10_tau_model(s, params)
        total += ((t_model - t_target) / tol) ** 2
    # soft physical priors:
    #  - tau_UV near Planck (Planck time ~ 10^-43.27 s)
    #  - dip depth must be >=0 (it is a DIP, not bump) and physically bounded
    #  - dip width physical (>0.5 dex)
    #  - cluster-window prior on s_dip (gentle Gaussian centred at log10 L_cluster ~ 22)
    pen = 0.0
    pen += ((logUV - (-43.27)) / 5.0) ** 2          # UV anchor near Planck
    if d < 0:
        pen += 1e3 * d * d                            # forbid negative depth (bump)
    if d > 5.0:
        pen += 1e3 * (d - 5.0) ** 2                   # physical: dip <= 5 dex
    if sig_dip <= 0.3:
        pen += 1e3 * (0.3 - sig_dip) ** 2
    if sig_dip > 6.0:
        pen += 1e3 * (sig_dip - 6.0) ** 2             # localized dip, not global tilt
    if w < 1.0:
        pen += 1e3 * (1.0 - w) ** 2                   # running width physical
    pen += ((s_dip - 22.0) / 4.0) ** 2               # cluster window prior
    return total + pen


def fit():
    rng = np.random.default_rng(42)
    best = (1e18, None)
    for trial in range(200):
        # initial guesses spanning physical scale
        x0 = np.array([
            rng.uniform(-50, -35),         # logUV near Planck region
            rng.uniform(2.0, 30.0),        # w (running width in dex)
            rng.uniform(15.0, 28.0),       # s_dip near cluster (log10 L ~ 22)
            rng.uniform(0.0, 4.0),         # depth (dex)
            rng.uniform(0.5, 8.0),         # sigma_dip (dex)
        ])
        try:
            res = minimize(chi2, x0, method="Nelder-Mead",
                           options={"xatol": 1e-6, "fatol": 1e-6, "maxiter": 8000})
            if res.fun < best[0] and np.isfinite(res.fun):
                best = (float(res.fun), res.x.copy())
        except Exception:
            continue
    if best[1] is None:
        return None
    return best


def report(best):
    chi2_val, p = best
    logUV, w, s_dip, d, sig_dip = p
    logIR = C_HOLO - logUV
    out = {
        "chi2_total": chi2_val,
        "params": {
            "log10_tau_UV": logUV,
            "log10_tau_IR_derived": logIR,
            "running_width_w_dex": w,
            "s_dip_log10Lm": s_dip,
            "dip_depth_dex": d,
            "sigma_dip_dex": sig_dip,
            "C_holo_fixed": C_HOLO,
        },
        "anchors": [],
    }
    all_pass = True
    for (name, s, t_target, tol) in ANCHORS:
        t_model = log10_tau_model(s, p)
        resid = t_model - t_target
        ok = abs(resid) <= tol
        all_pass &= ok
        out["anchors"].append({
            "name": name,
            "s_log10Lm": s,
            "target_log10_tau": t_target,
            "model_log10_tau": float(t_model),
            "residual_dex": float(resid),
            "tol_dex": tol,
            "pass": bool(ok),
        })
    out["all_pass"] = bool(all_pass)
    return out


def cluster_dip_test(p):
    """Verify dip naturally lands in cluster window [log10 L = 21..23]."""
    logUV, w, s_dip, d, sig_dip = p
    in_window = 21.0 <= s_dip <= 23.0
    has_depth = d > 0.3   # at least 0.3 dex
    return {
        "s_dip": float(s_dip),
        "depth_dex": float(d),
        "in_cluster_window_21_23": bool(in_window),
        "has_meaningful_depth": bool(has_depth),
        "natural_emergence": bool(in_window and has_depth),
    }


def main():
    print("L481: H1 = R3 (RG saddle FP) (X) R7 (Holographic UV-IR mixing)")
    print(f"Holographic constraint: log10(tau_UV)+log10(tau_IR) = {C_HOLO:.3f}")
    print("Fitting 4-value (cosmic, cluster, galactic, new_atomic)...")
    best = fit()
    if best is None:
        print("FIT FAIL")
        return
    rep = report(best)
    rep["cluster_dip_emergence"] = cluster_dip_test(best[1])

    out_dir = "/Users/blu/Desktop/spacetime-quantum-metabolism-hypothesis/results/L481"
    os.makedirs(out_dir, exist_ok=True)
    with open(os.path.join(out_dir, "fit_report.json"), "w") as f:
        json.dump(rep, f, indent=2)

    print(f"\nchi2_total = {rep['chi2_total']:.4f}")
    print("Anchor residuals:")
    for a in rep["anchors"]:
        flag = "PASS" if a["pass"] else "FAIL"
        print(f"  {a['name']:12s}  resid={a['residual_dex']:+.3f} dex  tol={a['tol_dex']:.2f}  [{flag}]")
    print(f"All-pass: {rep['all_pass']}")
    print(f"Cluster dip natural emergence: {rep['cluster_dip_emergence']['natural_emergence']}  "
          f"(s_dip={rep['cluster_dip_emergence']['s_dip']:.2f}, depth={rep['cluster_dip_emergence']['depth_dex']:.2f} dex)")

    # save curve
    s_grid = np.linspace(-12, 30, 600)
    curve = log10_tau_model(s_grid, best[1])
    np.savetxt(os.path.join(out_dir, "tau_curve.tsv"),
               np.c_[s_grid, curve], header="log10_L[m]\tlog10_tau_q[s]", delimiter="\t")
    print(f"Saved: {out_dir}/fit_report.json, tau_curve.tsv")


if __name__ == "__main__":
    main()
